export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CATEGORIES_LOADING = "CATEGORIES_LOADING";
export const CATEGORIES_ERR = "CATEGORIES_ERR";
export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS";
